name: Generate Repo Metrics Charts
on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  build-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # <-- add this
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true   # default, but explicit is fine
          ref: main

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib requests

      - name: Generate charts
        env:
          GH_TOKEN: ${{ secrets.STATS_TOKEN }}   # your PAT for API reads
          OWNER: kugendran-naidoo
          REPO: htakenote_DevOps
        run: python scripts/generate_metrics.py

      - name: Commit updated charts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(metrics): update charts"
          file_pattern: "metrics/*.png"
